# Generated by Django 5.0.3 on 2024-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('y1', 'سال اول'), ('y2', 'سال دوم'), ('y3', 'سال سوم')], default='y1', max_length=5)),
                ('stud_field', models.CharField(choices=[('computer', 'کامپیوتر'), ('chemical', 'شیمیایی')], default='computer', max_length=15)),
                ('sug_msg', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
