# Generated by Django 5.0.2 on 2024-02-26 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='time_for_slug',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
