# Generated by Django 5.0.2 on 2024-03-01 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articlemodel_slug_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='slug_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='زمان اسلاگ'),
        ),
    ]
