# Generated by Django 5.0.3 on 2024-03-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articlecommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecommentmodel',
            name='comment_msg',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
