# Generated by Django 5.0.3 on 2024-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articlecommentmodel_comment_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
