# Generated by Django 5.0.3 on 2024-03-11 19:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_alter_articlemodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا'),
        ),
    ]
