# Generated by Django 5.0.2 on 2024-02-29 19:13

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img/events/', verbose_name='عکس کاور')),
                ('body_pre', models.CharField(max_length=250, verbose_name='متن پیش نمایش')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.CharField(choices=[('draft', 'پبش نویس'), ('published', 'منتشر شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='آدرس')),
                ('time_for_slug', models.TimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='زمان انتشار')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_events', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
