# Generated by Django 5.0.2 on 2024-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='ایمیل')),
                ('fname', models.CharField(max_length=30, verbose_name='نام')),
                ('lname', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('age', models.PositiveSmallIntegerField(verbose_name='سن')),
                ('edu', models.CharField(max_length=15, verbose_name='تحصیلات')),
                ('pos', models.CharField(max_length=15, verbose_name='منصب')),
                ('img_prof', models.ImageField(upload_to='img/users/', verbose_name='عکس')),
                ('date_joined', models.DateTimeField(auto_now_add=True, unique=True, verbose_name='زمان پیوستن')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین ورود')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='سوپریوزر')),
                ('is_in_signup', models.BooleanField(default=True, verbose_name='در مرحله ی ثبت')),
                ('passwd', models.CharField(blank=True, max_length=200, null=True, verbose_name='رمز')),
                ('tmp_token', models.CharField(blank=True, max_length=10, null=True, verbose_name='توکن موقت')),
                ('tmp_token_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان توکن موقت')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
