# Generated by Django 5.0.2 on 2024-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='img_prof',
            field=models.ImageField(blank=True, null=True, upload_to='img/users/', verbose_name='عکس'),
        ),
    ]
