# Generated by Django 5.0.2 on 2024-02-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_edu_alter_usermodel_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='national_code',
            field=models.CharField(default='0000000000', max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
