# Generated by Django 5.0.2 on 2024-02-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_national_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='national_code',
            new_name='nat_code',
        ),
    ]
