"""
Django settings for sch project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# ========== IMPORTS ========== #
from pathlib import Path
import os
from os.path import join as os_path_join
# ========== ENDIMPORTS ========== #


# ========== ========== #
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
USER_WORK_SPACE = os.path.expanduser("~")
# ========== ========== #


# ========== ========== #
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vtns=pm1_2^1!oel5#)7pl$jx^znzew$)5s+r%48vq5no(c%i2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ["*"]
# ========== ========== #


# ========== INSTALLEDAPPS ========== #
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "users.apps.UsersConfig",
    "home.apps.HomeConfig",
    "copyr.apps.CopyrConfig",
    "errhandlers.apps.ErrhandlersConfig",
    "policy.apps.PolicyConfig",
    "articles.apps.ArticlesConfig",
    "news.apps.NewsConfig",
    "events.apps.EventsConfig",
    "contactus.apps.ContactusConfig",
    "sections.apps.SectionsConfig",
    "login.apps.LoginConfig",
    "suggestions.apps.SuggestionsConfig",
    "ckeditor",  # django-ckeditor
    "taggit", # django-taggit
    "jalali_date",  # persian datetime
]
# ========== ENDINSTALLEDAPPS ========== #


# ========== MIDDLEWARES ========== #
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# ========== ENDMIDDLEWARES ========== #


# ========== ROOTURL ========== #
ROOT_URLCONF = 'sch.urls'
# ========== ENDROOTURL ========== #


# ========== TEMPLATES ========== #
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# ========== ENDTEMPLATES ========== #


# ========== WSGI ========== #
WSGI_APPLICATION = 'sch.wsgi.application'
# ========== WSGI ========== #


# ========== DB ========== #
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# ========== ENDDB ========== #


# ========== PASSWDVALIDATION ========== #
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# ========== ENDPASSWDVALIDATION ========== #


# ========== INTERNATIONALIZATION ========== #
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
# ========== ENDINTERNATIONALIZATION ========== #


# ========== STATIC ========== #

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
# ========== ENDSTATIC ========== #


# ========== MEDIA ========== #
MEDIA_ROOT = os_path_join(BASE_DIR, "media/")
MEDIA_URL = "/media/"
# ========== ENDMEDIA ========== #


# ========== PK ========== #
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ========== ENDPK ========== #


# ========== USER ========== #
AUTH_USER_MODEL = "users.UserModel"
# ========== END ========== #


# ========== LOGGING ========== #

LOGGING = {
    "version": 1,
    "loggers": {
        "django": {
            "handlers": ["file", "console", "debughandler"],
            "level": "DEBUG",
        }
    },
    "handlers": {
        "file": {
            "level": "INFO",  # level set to INFO to just save useful logs
            "class": "logging.FileHandler",
            "filename": "./logs/logs.log",
            "formatter": "fileformatter",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "consoleformatter",
        },
        "debughandler": {
            "level": "DEBUG",  # level set to DEBUG to save all logs
            "class": "logging.FileHandler",
            "filename": f"{USER_WORK_SPACE}/logs/sch/debug.log",
            # "filename": "./logs/debug.log",
            "formatter": "fileformatter",
        },
    },
    "formatters": {
        "fileformatter": {
            # "format": "*** \n[{asctime}] ||| {levelname} ||| {name} ||| {module} ||| {message} \n***",
            "format": "<<<[{asctime}]  [{levelname}]  [{module}]  [{message}]>>>",
            "style": "{",
        },
        "consoleformatter": {
            "format": "***\n[{asctime}]  [{levelname}]  [{message}]\n***",
            "style": "{",
        }
    }
}
# ========== ENDLOGGING ========== #


# ========== CKEDITOR ========== #
CKEDITOR_UPLOAD_PATH = "ckfiles"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'


CKEDITOR_CONFIGS = {
    'default':
        {
            'toolbar': 'Custom',
            'width': 'auto',
            'extraPlugins': ','.join([
                'codesnippet',
            ]),
            'toolbar_Custom': [
                ["Source"],
                ["Save"],
                ["Cut", "Copy", "Paste"],
                ["Undo", "Redo"],
                ["Find", "Replace"],
                ["SelectAll"],
                ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript"],
                ["NumberedList", "BulletedList"],
                ["Outdent", "Indent"],
                ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],
                ["BidiLtr", "BidiRtl"],
                ["Link"],
                ["Image", "Table", "HorizontalRule", "Smiley", "SpecialChar", "Iframe"],
                ["Styles", "Format","FontSize"],
                ["TextColor", "BGColor"],
                ["Maximize"],
            ],
        },
}

# CKEDITOR_CONFIGS = {
#     'default':
#         {
#             'toolbar': 'full',
#             'width': 'auto',
#             'extraPlugins': ','.join([
#                 'codesnippet',
#             ]),
#         },
# }
# ========== ENDCKEDITOR ========== #
